# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOSMinimalCocoaPodsSample' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
end

target 'iOSMinimalCocoaPodsSampleTests' do

end

target 'iOSMinimalCocoaPodsSampleUITests' do

end
