source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOSMinimalCocoaPodsSample' do
  pod 'AFNetworking', '~> 3.0'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX.git', :commit => '854dd75998636ac54edc16f8e4f1f3918788c598' 
end

target 'iOSMinimalCocoaPodsSampleTests' do

end

target 'iOSMinimalCocoaPodsSampleUITests' do

end
