source "https://github.com/CocoaPods/Old-Specs"

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOSMinimalCocoaPodsSample' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX.git', :commit => 'a0372136fcc51ba84a5d8f065966ee6fea9b95de' 
end

target 'iOSMinimalCocoaPodsSampleTests' do

end

target 'iOSMinimalCocoaPodsSampleUITests' do

end
